feat/delivery-time
weDevsOfficial/dokan pull request #1184
Opened 2021-04-28 16:33 UTC by xaviranik

- Delivery time order details for vendor

2021-04-29 07:51 UTC, nurul-umbhiya commented on templates/orders/details.php
> +                            <?php if( ! empty( $delivery_time_date ) ): ?>
also check if module exists and if exists module is active

2021-06-18 11:02 UTC, shohag121 requested changes

2021-06-18 11:02 UTC, shohag121 commented on templates/orders/details.php
> +            <?php do_action( 'dokan_order_details_general_details_after', $order_id ); ?>
Getting merge conflict here. please check.

2021-06-18 11:06 UTC, nurul-umbhiya requested changes

2021-06-18 11:06 UTC, nurul-umbhiya commented on includes/functions.php
> +function dokan_format_date_time( $date = '', $format = false ) {
change function name with dokan_format_datetime()

2021-06-18 11:06 UTC, nurul-umbhiya commented on includes/Assets.php
> +                'i18n_date_format'                    => get_option( 'date_format' ),
use wc_date_format() instead of get_option( 'date_format' )

2021-06-30 07:58 UTC, shohag121 approved these changes

2021-06-30 09:33 UTC, merged