Fixed: Errors in Dokan Setting
weDevsOfficial/dokan pull request #1212
Opened 2021-05-24 01:14 UTC by SadikurSadik

2021-06-16 09:34 UTC, alamgircsebd approved these changes

2021-06-28 14:26 UTC, nurul-umbhiya requested changes

2021-06-28 14:26 UTC, nurul-umbhiya commented on includes/Admin/Settings.php
> +                $option_values['admin_percentage'] = wc_format_localized_price( isset( $option_values['admin_percentage'] ) ? $option_values['admin_percentage'] : 0 );
change this code like below;
```
$option_values['admin_percentage'] =  isset( $option_values['admin_percentage'] ) ? wc_format_localized_price( $option_values['admin_percentage'] ) : 0;
```

2021-06-28 14:26 UTC, nurul-umbhiya commented on includes/Admin/Settings.php
> +                $option_values['admin_percentage'] = wc_format_decimal( isset( $option_values['admin_percentage'] ) ? $option_values['admin_percentage'] : 0 );
follow above suggestion for this line of code too.

2021-06-29 10:27 UTC, closed without merging