feat: Orderby filtering for store product listing
weDevsOfficial/dokan pull request #1219
Opened 2021-06-01 07:26 UTC by alamgircsebd

Now user can shorting on single store product listing page

![Screenshot (40)](https://user-images.githubusercontent.com/25417335/120283335-e2e23000-c2dc-11eb-8db7-e83d544d927b.png)

2021-06-08 03:55 UTC, alamgircsebd commented
Also added product name search option on single store page
![image (1)](https://user-images.githubusercontent.com/25417335/121120547-95ffdb80-c83f-11eb-90e1-2703778f7519.png)

2021-06-24 07:04 UTC, alamgircsebd commented
Lastest design where have ajax product search box and autoload shorting
![Screenshot (46)](https://user-images.githubusercontent.com/25417335/123217733-b80a8680-d4ec-11eb-98dc-e0e7f5cb647d.png)

2021-06-28 15:08 UTC, nurul-umbhiya commented on includes/Assets.php
> +            'loading_img'        => plugins_url( 'assets/images/loading.gif', __FILE__ ),
this code will reference dokan/include/ folder, hence will output invalid file, why don't you use DOKAN_PLUGIN_ASSEST instead ?

2021-06-28 15:10 UTC, nurul-umbhiya commented on includes/Product/Hooks.php
> +        $get_postdata               = $_POST;
kindly don't use $get_postdata, instead use proper nonce verification and then use wp_unslash and proper sanitize function where necessary

2021-06-28 15:10 UTC, nurul-umbhiya commented on includes/Product/Hooks.php
> +        if ( ! isset( $get_postdata['_wpnonce'] ) || ! wp_verify_nonce( $get_postdata['_wpnonce'], 'dokan_store_product_search_nonce' ) ) {
move this code top of this function

2021-06-28 15:12 UTC, nurul-umbhiya commented on includes/Product/Hooks.php
> +            $querystr = "SELECT DISTINCT $wpdb->posts.*
since you are using custom sql query, could you please use prepare statement ?

2021-06-28 15:12 UTC, nurul-umbhiya commented on includes/Product/Hooks.php
> +        if ( isset( $get_postdata['search_term'] ) && ! empty( $get_postdata['search_term'] ) ) {
early return if this fields is not set

2021-06-28 15:13 UTC, nurul-umbhiya commented on includes/Product/Hooks.php
> +            if ( ! empty( $query_results ) ) {
early return if query result is empty

2021-06-28 15:14 UTC, nurul-umbhiya commented on includes/Product/Hooks.php
> +                ($wpdb->postmeta.meta_key = '_sku' AND $wpdb->postmeta.meta_value LIKE '%{$keyword}%')
what was the logic behind including _sku ?

2021-06-28 15:15 UTC, nurul-umbhiya commented on includes/Product/Hooks.php
> +            $querystr = "SELECT DISTINCT $wpdb->posts.*
you only need id fields form database, so use $wpdb->posts.ID

2021-06-28 15:17 UTC, nurul-umbhiya commented on includes/Product/Hooks.php
> +        if ( $output ) {
cache the output, coz there are lots of things happening here, also delete the cache, if vendor update any product

2021-06-28 15:20 UTC, nurul-umbhiya commented on includes/Product/Hooks.php
> +        $show_default_orderby    = 'menu_order' === apply_filters( 'dokan_default_store_products_orderby', get_option( 'woocommerce_default_catalog_orderby', 'menu_order' ) );
don't we need nonce verification here?

2021-06-29 15:34 UTC, nurul-umbhiya requested changes

2021-06-29 15:34 UTC, nurul-umbhiya commented on includes/Product/Hooks.php
> +        $store_id = intval( wp_unslash( $_POST['store_id'] ) );
use isset() before getting $_POST['store_id']

2021-06-29 15:34 UTC, nurul-umbhiya commented on includes/Product/Hooks.php
> +                ORDER BY posts.post_date DESC LIMIT 250",
250 limit is seems to high for product search, can we reduce it to 100?

2021-06-29 15:34 UTC, nurul-umbhiya commented on includes/Rewrites.php
> +            $orderby_value = isset( $_GET['product_orderby'] ) ? wc_clean( (string) wp_unslash( $_GET['product_orderby'] ) ) : wc_clean( get_query_var( 'product_orderby' ) );
type casting to (string) is unnecessary here

2021-06-29 15:34 UTC, nurul-umbhiya commented on includes/Rewrites.php
> +            if ( isset( $_GET['product_name'] ) && ! empty( $_GET['product_name'] ) ) {
can't we do nonce checking here since we are using $_GET data??

2021-06-29 15:34 UTC, nurul-umbhiya commented on includes/Rewrites.php
> +            $orderby_value = isset( $_GET['product_orderby'] ) ? wc_clean( (string) wp_unslash( $_GET['product_orderby'] ) ) : wc_clean( get_query_var( 'product_orderby' ) );
can we get $orderby and $order value from function argument? this way we don't need to nonce checking and we can use this function somewhere else

2021-06-29 15:36 UTC, nurul-umbhiya commented
Also think about this pr also: https://github.com/weDevsOfficial/dokan-pro/pull/1321#discussion_r660662816

2021-06-30 09:38 UTC, nurul-umbhiya approved these changes

2021-06-30 09:38 UTC, merged