Test/automation
weDevsOfficial/dokan pull request #1268
Opened 2021-07-06 09:18 UTC by shanjidah

Add autologin on Dokan automation script.
Add ReadMe.md to set a guideline for configuration how to run an automation script on Dokan Plugin

2021-08-16 06:27 UTC, FaraziF requested changes
Please review the feedback & fix it as soon as possible.

2021-08-16 06:27 UTC, FaraziF commented on tests/e2e/core-tests/group_01_product_explore_test.js
> +    loginAs('vendor');
Maintain upper and lower case for the user role because the user is case sensitive.

2021-08-16 06:27 UTC, FaraziF commented on tests/e2e/core-tests/group_02_product_func_test.js
> +    loginAs('vendor');
Maintain upper and lower case for the user role because the user is case sensitive.

2021-08-16 06:27 UTC, FaraziF commented on tests/e2e/core-tests/orders_01_single_test.js
> +    loginAs('customer');
Maintain upper and lower case for the user role because the user is case sensitive.

2021-08-16 06:27 UTC, FaraziF commented on tests/e2e/core-tests/orders_02_multiple_test.js
> +    loginAs('customer');
Maintain upper and lower case for the user role because the user is case sensitive.

2021-08-16 06:27 UTC, FaraziF commented on tests/e2e/core-tests/orders_03_multiple_vendor_test.js
> +    loginAs('customer');
Maintain upper and lower case for the user role because the user is case sensitive.

2021-08-16 06:27 UTC, FaraziF commented on tests/e2e/core-tests/product_group_01_explore_test.js
> +    loginAs('vendor');
Maintain upper and lower case for the user role because the user is case sensitive.

2021-08-16 06:27 UTC, FaraziF commented on tests/e2e/core-tests/product_group_02_functionality_test.js
> +    loginAs('vendor');
Maintain upper and lower case for the user role because the user is case sensitive.

2021-08-16 06:27 UTC, FaraziF commented on tests/e2e/core-tests/product_simple_01_explore_test.js
> +    loginAs('vendor');
Maintain upper and lower case for the user role because the user is case sensitive.

2021-08-16 06:27 UTC, FaraziF commented on tests/e2e/core-tests/product_simple_02_product_functionality_test.js
> +    loginAs('vendor');
Maintain upper and lower case for the user role because the user is case sensitive.

2021-08-16 06:27 UTC, FaraziF commented on tests/e2e/example.codecept.conf.js 
> +    },
follow the code structure

2021-08-16 06:27 UTC, FaraziF commented on tests/e2e/README.md
> +git clone https://github.com/shanjidah/dokan.git
End-user don't pull your repo

2021-08-18 09:14 UTC, shanjidah commented
Resolved all issues

2021-08-23 08:09 UTC, merged