New Rest Route To Get Corresponding Vendors Product Categories Under StoreController
weDevsOfficial/dokan pull request #1290
Opened 2021-08-12 18:42 UTC by nurul-umbhiya

new: added a new method named get_published_products() under Vendor class to get all published products of a vendor
new: added a new method named get_store_categories() under Vendor class to get all published products assigned categories
new: added a new rest route name id/categories under StoreController to get corresponding vendors published product categories

2021-08-16 03:17 UTC, nurul-umbhiya commented
@shanjidah kindly consult with me before testing this PR

2021-08-17 05:33 UTC, FaraziF commented
On the vendor store page, display the deleted categories from the store product category.

2021-08-17 07:54 UTC, nurul-umbhiya commented
@FaraziF bhai fixed.

2021-08-25 05:29 UTC, xaviranik requested changes

2021-08-25 05:29 UTC, xaviranik commented on includes/REST/StoreController.php
> +     * @since 3.2.11
Kindly replace with `DOKAN_PRO_SINCE`

2021-08-25 05:29 UTC, xaviranik commented on includes/Vendor/Vendor.php
> +     * @since 3.2.11
Kindly replace with DOKAN_PRO_SINCE

2021-08-25 05:29 UTC, xaviranik commented on includes/Vendor/Vendor.php
> +     * @since 3.2.11
Kindly replace for all `@since` with `DOKAN_PRO_SINCE`

2021-08-25 05:32 UTC, xaviranik approved these changes

2021-08-25 06:05 UTC, merged