Feature/integration of sweetalert2 for confirmation alert
weDevsOfficial/dokan pull request #1328
Opened 2021-09-14 10:10 UTC by abdulhadicse

Previously we used window.alert and window.confirm for confirmation alert system, which is going to be deprecated in near future.

So, in this branch, we have integrated sweetalert2 for confirmation alert.

Fix: #1283

2021-09-15 11:52 UTC, xaviranik requested changes

2021-09-23 06:27 UTC, xaviranik requested changes

2021-09-23 06:27 UTC, xaviranik commented on assets/src/js/helper.js
> + * @param {object} [options] Configuration of sweet alert.
Kindly write {object} [options] to elaborate which parameters are expected in the object.

2021-09-23 06:27 UTC, xaviranik commented on assets/src/js/helper.js
> + * @since DOKAN_LITE
Kindly remove DOKAN_LITE and manually manage the version

2021-09-24 09:07 UTC, ManiruzzamanAkash commented on assets/src/js/orders.js
> +                let isRefund = await dokan_sweet_alert( dokan_refund.i18n_do_refund, { action : 'confirm' }  );
if the variable used only once and not being updated, use `const` instead of `let`

2021-09-24 09:07 UTC, ManiruzzamanAkash commented on assets/src/js/product-editor.js
> +                let isRemoved = await dokan_sweet_alert( dokan.remove_attribute, { action : 'confirm' } );
Same here, use `const`, instead of `let` 
since, it doesn't updated anywhere.

2021-10-05 05:49 UTC, closed without merging