fix: set & update store open close time in a specific format & store open close settings make extendable for pro.
weDevsOfficial/dokan pull request #1386
Opened 2021-10-27 05:46 UTC by MdAsifHossainNadim

### Update store open close settings

- Use filters and actions for make extendable our store open close feature in "templates/settings/store-form.php".
- Optimize dokan_store_time code and make 12 hour format data for save in "includes/Dashboard/Templates/Settings.php".
- Compare store opening/closing data in 12 hour format and update dokan_is_store_open function for extendable.

Related with dokan-pro: <a href='https://github.com/weDevsOfficial/dokan-pro/pull/1559'>https://github.com/weDevsOfficial/dokan-pro/pull/1559/</a>
fix: https://github.com/weDevsOfficial/dokan/issues/1410

2021-11-05 06:55 UTC, ManiruzzamanAkash commented on includes/Dashboard/Templates/Settings.php
> +                $current_day['opening_time']  = isset( $opening_time ) ? $opening_time : '';
I think there would be no possibility for `$opening_time` become unsetted in here. So, `isset()` is not necessary. Please recheck again. Same for `$closing_time`

2021-11-05 06:55 UTC, ManiruzzamanAkash commented on includes/functions.php
> +    $profile_info       = dokan_get_store_info( dokan_get_current_user_id() );
make this variable name `$store_info`

2021-11-05 06:55 UTC, ManiruzzamanAkash commented on includes/functions.php
> +function dokan_get_store_closing_time( $current_day, $index = 0 ) {
These two functions implement almost same type of things. We should follow the `DRY concept`. Better would be, create just one function. And we could also generate two function from these in future.
```php

/*
* @params string $time_type, eg: `opening_time` or `closing_time`
*/
function dokan_get_store_time( $time_type, $current_day ) { // You don't use the index anywhere also, so why's that?
     
  // just some snippet would be like this - 
  $store_time = isset( $store_info['dokan_store_time'] ) ? $store_info['dokan_store_time'] : '';
  $time       = isset( $store_time[ $current_day ][$time_type] ) ? $store_time[ $current_day ][$time_type] : '';
 // do rest as this
}
```

Then in future use case - 
```php
dokan_get_store_time( 'opening_time', 1 );
dokan_get_store_time( 'closing_time', 1 );
```

2021-11-05 06:55 UTC, ManiruzzamanAkash commented on templates/settings/store-form.php
> +                            <label for="closing-time" class="time" style="visibility: <?php echo isset( $status ) && $status == 'open' ? 'visible' : 'hidden'; ?>" >
This for will not work in `<label for="opening-time" >`

Remember, why we use this `for`. We need the id in the input same name as this. Then, on click this label, the input will be focused. 

Talk with me, if you have any confusion.

2021-11-05 06:55 UTC, ManiruzzamanAkash commented on templates/settings/store-form.php
> +                            <label for="opening-time" class="time" style="visibility: <?php echo isset( $status ) && $status == 'open' ? 'visible' : 'hidden'; ?>" >
For `for=""` in `label` please check the below note.

2021-11-05 06:55 UTC, ManiruzzamanAkash commented on templates/settings/store-form.php
> +                                    $dokan_store_closing_entities = sprintf( '<input type="text" class="dokan-form-control closing-time" name="closing_time[%1$s]" id="closing-time[%1$s]" placeholder=
Why `esc_attr` in static string - `esc_attr( '00:00' ) `?

2021-11-05 06:55 UTC, ManiruzzamanAkash commented on templates/settings/store-form.php
> +                let selectedWorkingStatus = $(this).find( '.dokan-on-off option[selected]' ).length;
make this `selectedWorkingStatus ` variable type as `const`.

2021-11-05 06:55 UTC, ManiruzzamanAkash commented on templates/settings/store-form.php
> +            let self       = $(this),
use, like `$( this )`
and
make all of the variable with `const` as, you wouldn't change these later.

2021-11-05 06:55 UTC, ManiruzzamanAkash commented on templates/settings/store-form.php
> +            let self      = $(this),
please do the same here, as top.

2021-11-05 09:56 UTC, tanmayjay requested changes

2021-11-05 09:56 UTC, tanmayjay commented on includes/Dashboard/Templates/Settings.php
> +            $location         = ! empty( $_POST['find_address'] ) ? wc_clean( wp_unslash( $_POST['location'] ) ) : $default_location;
Why are you checking `empty` on `$_POST['find_address']` whereas you are using the value of `$_POST['location']`?
And also, as others above said, `wc_clean` is not needed everywhere.

2021-11-05 09:56 UTC, tanmayjay commented on includes/functions.php
> +function dokan_get_translated_days( $days = true ) {
As you have stored the `key => value` pair in the variable, it's no more necessary to check all the key manually. You can rewrite the function the following way:

```
function dokan_get_translated_days( $day = '' ) {
    $all_days = array(
        'sunday'    => __( 'Sunday', 'dokan-lite' ),
        'monday'    => __( 'Monday', 'dokan-lite' ),
        'tuesday'   => __( 'Tuesday', 'dokan-lite' ),
        'wednesday' => __( 'Wednesday', 'dokan-lite' ),
        'thursday'  => __( 'Thursday', 'dokan-lite' ),
        'friday'    => __( 'Friday', 'dokan-lite' ),
        'saturday'  => __( 'Saturday', 'dokan-lite' ),
    );

    if ( empty( $day ) ) {
        return $all_days;
    }

    if ( isset( $all_days[ $day ] ) ) {
        return $all_days[ $day ];
    }

    if ( 'close' === $day ) {
        return apply_filters( 'dokan_store_close_day_label', __( 'Off Day', 'dokan-lite' ) );
    }

    return apply_filters( 'dokan_get_translated_days', '', $day );
}
```

2021-11-05 09:58 UTC, tanmayjay requested changes

2021-11-05 09:58 UTC, tanmayjay commented on includes/functions.php
> +function dokan_get_translated_days( $day = null ) {
As you have stored the `key => value` pair in the variable, it's no more necessary to check all the key manually. You can rewrite the function the following way:

```
function dokan_get_translated_days( $day = '' ) {
    $all_days = array(
        'sunday'    => __( 'Sunday', 'dokan-lite' ),
        'monday'    => __( 'Monday', 'dokan-lite' ),
        'tuesday'   => __( 'Tuesday', 'dokan-lite' ),
        'wednesday' => __( 'Wednesday', 'dokan-lite' ),
        'thursday'  => __( 'Thursday', 'dokan-lite' ),
        'friday'    => __( 'Friday', 'dokan-lite' ),
        'saturday'  => __( 'Saturday', 'dokan-lite' ),
    );

    if ( empty( $day ) ) {
        return $all_days;
    }

    if ( isset( $all_days[ $day ] ) ) {
        return $all_days[ $day ];
    }

    if ( 'close' === $day ) {
        return apply_filters( 'dokan_store_close_day_label', __( 'Off Day', 'dokan-lite' ) );
    }

    return apply_filters( 'dokan_get_translated_days', '', $day );
}
```

2021-11-05 11:46 UTC, ManiruzzamanAkash approved these changes

2021-11-09 11:40 UTC, tanmayjay approved these changes

2021-12-08 18:07 UTC, tanmayjay requested changes

2021-12-08 18:07 UTC, tanmayjay commented on includes/Dashboard/Templates/Settings.php
> +                $current_day['status'] = $store_status;
This line is not needed here.

2021-12-08 18:07 UTC, tanmayjay commented on includes/Dashboard/Templates/Settings.php
> +                    $dokan_store_time[ $day_key ] = $current_day;
You could just reduce this as below:
```
                    $dokan_store_time[ $day_key ] = [
                        'status'       => 'close',
                        'opening_time' => '',
                        'closing_time' => '',
                    ];
```

2021-12-08 18:07 UTC, tanmayjay commented on includes/Dashboard/Templates/Settings.php
> +                $dokan_store_time[ $day_key ] = $current_day;    // Make dokan store time data here.
Mentioned above to reduce variables.

2021-12-09 18:21 UTC, tanmayjay requested changes

2021-12-09 18:21 UTC, tanmayjay commented on includes/functions.php
> +    if ( ! empty( $dokan_closing_time ) && is_array( $dokan_closing_time ) ) {
Rewrite this part as below:
```
        if ( empty( $dokan_closing_time ) ) {
            return '';
        }

        if ( ! is_array( $dokan_closing_time ) ) {
            return $dokan_closing_time;
        }

        if ( isset( $dokan_closing_time[ $index ] ) ) {
            return $dokan_closing_time[ $index ];
        }

        return $dokan_closing_time[0]; // return the 1st index or the whole array according to your need
```

2021-12-10 15:07 UTC, tanmayjay approved these changes

2021-12-10 15:09 UTC, tanmayjay approved these changes

2022-01-03 11:30 UTC, Rat01047 commented
Issue:
Scenario:
The Opening and Closing time headers are given as Opening times* and Closing times* which does not apply for single Opening and Closing time.

Steps to Reproduce:
1. Vendor -> Dashboard -> Settings -> Store
2. Enable "Store Opening Closing Time"
3. Select day > Time selectors headers 
4. For single time selections it shows > Opening times - Closing times

Expected Result:
The Opening times* and Closing times* should be given as Opening time(s) and Closing time(s), for presenting that there are 1+ option for adding times.

Screenshot for reference:
![image](https://user-images.githubusercontent.com/95366111/147925351-175c326b-d2ac-4e4e-90c9-247f5151cd6a.png)

2022-01-28 08:06 UTC, merged