Feat: added-necessary-tooltips-for-dokan-settings
weDevsOfficial/dokan pull request #1390
Opened 2021-11-01 03:42 UTC by MdAsifHossainNadim

### Added Necessary Tooltips for Dokan Settings

- Updates Fields.vue for get tooltips in frontend.
- Push tooltips from dokan-lite settings for show specific fields tooltip.
- Update admin.less for design.

https://user-images.githubusercontent.com/90011088/139616650-8f8d8552-3782-40ca-9b57-b1bfa893a7e3.png

2021-11-04 02:46 UTC, SadikurSadik requested changes

2021-11-04 02:46 UTC, SadikurSadik commented on includes/Admin/Settings.php
> +                    'tool_tips' => true,
Indentation problem

2021-11-04 02:46 UTC, SadikurSadik commented on src/admin/components/Fields.vue
> +                     <label :for="sectionId + '[' + fieldData.name + ']'">
unnecessary extra spaces

2021-11-04 08:36 UTC, rajankarmakar commented on assets/src/less/admin.less
> +  width: 235px;
Try to use ( em or rem ) unit instead of px. This would be better for responsiveness.

2021-11-04 08:55 UTC, SadikurSadik approved these changes

2021-11-05 02:54 UTC, rajankarmakar approved these changes

2021-11-10 07:02 UTC, nurul-umbhiya approved these changes

2021-11-24 04:47 UTC, SadikurSadik requested changes

2021-11-24 04:47 UTC, SadikurSadik commented on includes/Admin/Settings.php
> +                    'tooltip' => __( 'Check to add available payment methods for vendors to withdraw money.', 'dokan' ),
Text domain should be `dokan-lite`

2021-11-24 04:47 UTC, SadikurSadik commented on includes/Admin/Settings.php
> +                    'tooltip' => __( 'If checked, vendors will not be prompted through a guided set up process but redirected straight to the vendor dashboard.', 'dokan-lite' ),
`set up` should be `setup`

2021-11-24 07:02 UTC, SadikurSadik approved these changes

2021-11-26 10:56 UTC, merged