Fix/update refund and withdraw database table column
weDevsOfficial/dokan pull request #1391
Opened 2021-11-01 06:40 UTC by rajankarmakar

There was a bug when a user missed to run the upgrader after a couple of releases if the user run the data upgrader the database does not upgrade as expected.

2021-11-05 04:34 UTC, devAsadNur requested changes

2021-11-05 04:34 UTC, devAsadNur commented on includes/Upgrade/Upgrades/V_3_3_1.php
> +     * @since DOKAN_LITE_SINCE
Instead of `DOKAN_LITE_SINCE`, please use possible upcoming version number.

2021-11-05 04:34 UTC, devAsadNur commented on includes/Upgrade/Upgrades/V_3_3_1.php
> +     * Updates withdraw database table column
Here, it should be `refund database` instead of `withdraw database`. Please fix it.

2021-11-05 04:48 UTC, devAsadNur commented on includes/Upgrade/Upgrades/V_3_3_1.php
> +     * @since DOKAN_LITE_SINCE
Same as above, instead of `DOKAN_LITE_SINCE`, please consider using possible upcoming version number.

2021-11-05 19:29 UTC, tanmayjay requested changes

2021-11-05 19:29 UTC, tanmayjay commented on includes/Upgrade/Upgrades/V_3_3_1.php
> +        if ( ! empty( $existing_columns ) ) {
You don't need to check if it is empty. Just cast the `$existing_columns` by `array` while running foreach loop. As the `$wpdb::get_results` method return `array|object|null`, if the value is null, the array casting will convert it into an empty array and for empty array the foreach loop will not run automatically.
Rewrite this in the following way:

```
    foreach ( (array) $existing_columns as $existing_column ) {
        if (
            'text' !== $existing_column->Type &&
            (
                'item_totals' === $existing_column->Field ||
                'item_tax_totals' === $existing_column->Field
            )
        ) {
            $wpdb->query(
                "ALTER TABLE `{$wpdb->prefix}dokan_refund` MODIFY COLUMN {$existing_column->Field} text" // phpcs:ignore
            );
        }
    }
```

2021-11-08 03:19 UTC, tanmayjay approved these changes

2021-11-08 03:24 UTC, devAsadNur approved these changes

2021-11-10 12:05 UTC, nurul-umbhiya commented on includes/Upgrade/Upgrades/V_3_3_1.php
> +                'text' !== $existing_column->Type && // phpcs:ignore
rearrange this condition like below:
```
if ( in_array( $existing_column->Field, [ 'item_totals', 'item_tax_totals' ], true ) && 'text' !== $existing_column->Type )

```

2021-11-11 09:05 UTC, nurul-umbhiya approved these changes

2021-11-11 09:57 UTC, nurul-umbhiya approved these changes

2021-11-11 09:58 UTC, merged