Fix/vendor store per page placeholder
weDevsOfficial/dokan pull request #1396
Opened 2021-11-04 03:20 UTC by rajankarmakar

There was an issue on the vendor settings page. On the Store Products Per Page setting field the placeholder was hardcoded with the number 10. Which is confusing for vendors to understand.

fix #1375

2021-11-04 03:31 UTC, SadikurSadik approved these changes

2021-11-05 04:04 UTC, alamgircsebd requested changes

2021-11-05 04:04 UTC, alamgircsebd commented on templates/settings/store-form.php
> +                <input id="dokan_store_ppp" value="<?php ! empty( $store_ppp ) ? esc_attr_e( $store_ppp, 'dokan-lite' ) : ''; ?>" name="dokan_store_ppp" placeholder="<?php esc_attr_e( 'Enter the numb
here no need to use localization `esc_attr_e( $store_ppp, 'dokan-lite' )`

2021-11-05 04:23 UTC, alamgircsebd approved these changes

2021-11-10 11:46 UTC, nurul-umbhiya commented on templates/settings/store-form.php
> +                <input id="dokan_store_ppp" value="<?php ! empty( $store_ppp ) ? esc_attr( $store_ppp ) : ''; ?>" name="dokan_store_ppp" placeholder="<?php esc_attr_e( 'Enter the number of products',
change placeholder text

2021-11-11 08:48 UTC, nurul-umbhiya commented on templates/settings/store-form.php
> +                <input id="dokan_store_ppp" value="<?php ! empty( $store_ppp ) ? esc_attr( $store_ppp ) : ''; ?>" name="dokan_store_ppp" placeholder="<?php esc_attr_e( 'Enter the number of products',
Number of products to display  on store page

2021-11-11 09:55 UTC, nurul-umbhiya approved these changes

2021-11-11 09:55 UTC, merged