Feat/price quantity base commission
weDevsOfficial/dokan pull request #1421
Opened 2021-11-17 02:49 UTC by Aunshon

2021-12-30 06:28 UTC, shanjidah commented
**Scenario1:** Deleted all commission types as Product price, shows console error.

**Here is the screenshot:**

<img width="1272" alt="Screen Shot 2021-12-30 at 12 23 52 PM" src="https://user-images.githubusercontent.com/37714632/147727149-1edcd52a-26b8-4683-b47b-151607d05312.png">

2021-12-30 06:32 UTC, shanjidah commented
Scenario2: Commission Label is not matched with Commission types Functionalities.

<img width="803" alt="Screen Shot 2021-12-30 at 12 30 47 PM" src="https://user-images.githubusercontent.com/37714632/147727405-260340a8-5f7a-42d2-b5c5-fdefb68a88c2.png">

2021-12-30 11:01 UTC, shanjidah commented
Scenario 3: Commission type is not working on Vendor Profile.

<img width="1277" alt="Screen Shot 2021-12-30 at 4 58 16 PM" src="https://user-images.githubusercontent.com/37714632/147746146-3f916ff8-585e-49cd-825a-a07e175d711e.png">

2022-04-20 05:00 UTC, tanmayjay requested changes

2022-04-20 06:14 UTC, tanmayjay requested changes

2022-04-20 06:14 UTC, tanmayjay commented on src/admin/components/Fields/SinglePriceQuantityVendorSale.vue
> +            this.$refs[`dokan-${this.selectedCommissionLabel}-from-msg${index}`][0].innerText = `Must be more or equal ${from}`;
The text should be translatable. And the sentence will be `Must be more than or equal to `

2022-04-20 06:14 UTC, tanmayjay commented on src/admin/pages/VendorPaymentFields.vue
> +            } else {
`else` is not needed here. Just write `return ''`

2022-04-20 06:14 UTC, tanmayjay commented on src/admin/pages/VendorPaymentFields.vue
> +        // async generateNextRow( data ) {
Remove this if not needed.

2022-04-20 06:14 UTC, tanmayjay commented on templates/settings/new-commission.php
> +$commission_i18n_data = [
Why do you need this? You can use the values directly inside html.

2022-04-20 06:14 UTC, tanmayjay commented on templates/settings/new-commission.php
> +                <div class="dokan-new-commission-col-commission"><?php esc_html_e( $commission_i18n_data['commission'] ); ?></div>
text domain is missing for all the `esc_html_e`

2022-04-20 06:14 UTC, tanmayjay commented on templates/settings/new-commission.php
> +if ( ! empty( get_current_screen()->id ) && 'user-edit' === get_current_screen()->id ) {
Remove this from here and use this inside another relevant file.

2022-04-20 06:14 UTC, tanmayjay commented on templates/settings/new-commission.php
> +if ( ! empty( get_current_screen()->id ) && 'user-edit' === get_current_screen()->id ) {
Also, from the line#78, do that using `wp_localize_script`

2022-04-25 09:22 UTC, tanmayjay requested changes

2022-04-26 08:14 UTC, tanmayjay approved these changes

2023-06-19 03:07 UTC, closed without merging

2023-06-19 03:07 UTC, nurul-umbhiya commented
Requirements have been updated. Need to provide a new pr.