Dokan new change log
weDevsOfficial/dokan pull request #1425
Opened 2021-11-19 11:23 UTC by shahadat015

2021-11-19 11:53 UTC, rajankarmakar commented on includes/REST/ChangeLogController.php
> +    protected $base = '';
What is the use of this $base variable as it does not use anywhere?

2021-11-19 11:53 UTC, rajankarmakar commented on includes/REST/ChangeLogController.php
> +                    'callback'            => array( $this, 'get_change_log' ),
Try to use a shorthand array everywhere.

2021-11-19 11:53 UTC, rajankarmakar commented on src/admin/router/index.js
> +    scrollBehavior (to, from, savedPosition) {
Do not use space before opening ( bracket.

2021-11-22 02:41 UTC, devAsadNur requested changes

2021-11-22 02:41 UTC, devAsadNur commented on assets/src/less/admin.less
> +  font-style: normal;
Please use 4 spaces instead of 2 spaces for indenting CSS properties in all of the above lines.

2021-11-22 02:41 UTC, devAsadNur commented on includes/REST/Manager.php
> +                DOKAN_DIR . '/includes/REST/ChangeLogController.php'             => '\WeDevs\Dokan\REST\ChangeLogController',
Please use proper indentation as per the above lines.

2021-11-22 05:35 UTC, devAsadNur approved these changes

2021-12-09 03:26 UTC, closed without merging