fix(Order): create order API with coupon lines
weDevsOfficial/dokan pull request #1441
Opened 2021-12-03 15:39 UTC by jamesbechet

# What this PR does
Fixes crash when creating an order using the woocommerce API with coupon lines.

## The stack trace
```
[03-Dec-2021 15:32:20 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_cart() on null in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/dokan-lite/includes/Order/Hooks.php:284
Stack trace:
#0 /Applications/MAMP/htdocs/wordpress/wp-includes/class-wp-hook.php(303): WeDevs\Dokan\Order\Hooks->ensure_vendor_coupon(true, Object(WC_Coupon), Object(WC_Discounts))
#1 /Applications/MAMP/htdocs/wordpress/wp-includes/plugin.php(189): WP_Hook->apply_filters(true, Array)
#2 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/woocommerce/includes/class-wc-discounts.php(962): apply_filters('woocommerce_cou...', true, Object(WC_Coupon), Object(WC_Discounts))
#3 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/woocommerce/includes/class-wc-discounts.php(252): WC_Discounts->is_coupon_valid(Object(WC_Coupon))
#4 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(1132): WC_Discounts->apply_coupon(Object(WC_Coupon))
#5 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/woocommer in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/dokan-lite/includes/Order/Hooks.php on line 284
```

## The crash
![Screen Shot 2021-12-03 at 10 35 31 AM](https://user-images.githubusercontent.com/2947763/144630075-796832b8-480e-4cf5-9719-1fd002eef146.png)

2022-01-27 06:48 UTC, tanmayjay requested changes

2022-01-27 06:48 UTC, tanmayjay commented on includes/Order/Hooks.php
> +        if (WC()->cart) {
Kindly rewrite it in the following way:

```
            if ( WC()->cart ) {
                foreach ( WC()->cart->get_cart() as $item ) {
                    $product_id           = $item['data']->get_id();
                    $available_vendors[]  = (int) get_post_field( 'post_author', $product_id );
                    $available_products[] = $product_id;
                }
            } else {
                foreach ( $discount->get_items() as $product_id => $item ) {
                    $available_vendors[]  = (int) get_post_field( 'post_author', $product_id );
                    $available_products[] = $product_id;
                }
            }
```

2022-01-27 15:09 UTC, jamesbechet commented on includes/Order/Hooks.php
> +        if (WC()->cart) {
@tanmayjay all set

2022-01-27 17:56 UTC, tanmayjay approved these changes

2022-02-24 04:06 UTC, nurul-umbhiya approved these changes

2022-02-28 05:03 UTC, merged