enhance/display-store-times-in-vendor-store-page
weDevsOfficial/dokan pull request #1517
Opened 2022-01-26 17:04 UTC by MdAsifHossainNadim

### Display vendor store times in vendor store.
Previous this enhancement, In the vendor store page has no reflection of the Day & time set by the Vendor on the Store, only "Store is open/closed" message is shown.

Now, after this enhancement vendor can show his stores all opening & closing times.

**Dependency with dokan-lite:**
https://github.com/weDevsOfficial/dokan/pull/1386

fix: https://github.com/weDevsOfficial/dokan-pro/issues/1693

2022-02-14 11:02 UTC, xaviranik requested changes

2022-02-24 05:29 UTC, nurul-umbhiya requested changes

2022-02-24 05:29 UTC, nurul-umbhiya commented on templates/store-header.php
> +$dokan_store_info         = dokan_get_store_info( $store_user->get_id() );
we already have $store_info under line 3

2022-02-25 04:43 UTC, Rat01047 commented
Issue: The Dropdown option is not working properly.
Scenario: The Dropdown for showing Store Opening Closing is not displaying information correctly.

Screenshot for reference:
![image](https://user-images.githubusercontent.com/95366111/155655109-406d4143-b121-471d-b3d5-c6edf667ef60.png)

2022-02-25 06:42 UTC, Rat01047 commented
Issue: Dokan-Lite Dropdown view is different from Pro.
Scenario: When checking on Dokan-Lite only the Dropdown option display is different compared to Dokan-Pro.

Screenshot given for reference:
![image](https://user-images.githubusercontent.com/95366111/155667349-8d29fd58-76f6-44f2-b804-8d5f94b63b87.png)

2022-02-28 03:27 UTC, merged