Fix/solved vendor store settings validation error
weDevsOfficial/dokan pull request #1567
Opened 2022-03-09 09:56 UTC by MdAsifHossainNadim

### Solved vendor store settings field validation error.

Previous this fix, find an error in the console when we type in the phone number field in the seller store settings.
Now, It's fine.

fix: https://github.com/weDevsOfficial/dokan-pro/issues/1811

2022-04-01 06:42 UTC, tanmayjay requested changes

2022-04-01 06:42 UTC, tanmayjay commented on templates/settings/store-form.php
> +                    (e.keyCode >= 35 && e.keyCode <= 39)
Make sure the key range here is correct.

2022-04-01 06:42 UTC, tanmayjay commented on templates/settings/store-form.php
>                      (e.keyCode == 65 && e.ctrlKey === true) ||
This keycode also could be stored in a variable to understand which key it is.

2022-05-12 02:43 UTC, shashwatahalder01 commented
@MdAsifHossainNadim vai, this fix doesn't work for the AZERTY keyboard layout.

2022-05-13 06:08 UTC, merged