Enhance/payment page dorpdown and back button
weDevsOfficial/dokan pull request #1608
Opened 2022-04-28 09:52 UTC by NAbdulla1

### All Submissions:

* [x] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [x] My code satisfies feature requirements
* [x] My code is tested
* [x] My code passes the PHPCS tests
* [x] My code has proper inline documentation
* [ ] I've included developer documentation (optional)
* [x] I've added proper labels to this pull request

### Changes proposed in this Pull Request:
Enhance UI of payment page
add back link from payment settings page.

https://user-images.githubusercontent.com/21087073/165726760-22f95671-f8f4-4a57-8130-2cc5a3d1d4fb.mp4

![image](https://user-images.githubusercontent.com/21087073/165726641-10ddd273-5ed3-482f-8e98-d4159708e9b6.png)

Closes [Dokan pro issue 1860](https://github.com/weDevsOfficial/dokan-pro/issues/1860)
### How to test the changes in this Pull Request:

1. Go to Vendor Dashboard > settings > payment
2. see the improved dropdown
3. click on a method from dorpdown
4. see 'Back' link at the top left corner, 

### Changelog entry

> **enhance:** improved UI of Payment settings page

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

2022-05-06 22:36 UTC, tanmayjay requested changes

2022-05-06 22:36 UTC, tanmayjay commented on templates/settings/payment.php
> +                                    <a href="<?php echo esc_url( home_url( "dashboard/settings/payment/manage-" . $method_key ) ); ?>">
use `dokan_get_page_url`

2022-05-13 05:29 UTC, Rat01047 commented
Issue-1: 
Payment Settings Page Design Break

Scenario: Vendor Dashboard > Payment Settings Page > Design Break + Text not showing properly

Screenshot for reference:
![image](https://user-images.githubusercontent.com/95366111/168216920-783292ad-df89-4194-9615-1b7be087a612.png)

2022-05-13 05:30 UTC, Rat01047 commented
Issue-2: 
Payment Setup page Design break on Bank Transfer for a new Vendor
 
Scenario: Create New Vendor > Payment Setup page > Design break for Bank Transfer
 

Screenshot for reference:
![image](https://user-images.githubusercontent.com/95366111/168217275-9b603764-f62c-4de4-b862-9350e366f1ab.png)

2022-05-16 09:27 UTC, Rat01047 commented
Issue-3:
Payment Setup page Design break on Bank Transfer for a new Vendor

Scenario: Create New Vendor > Payment Setup page > Design break for Bank Transfer


Screenshot given for reference:
![image](https://user-images.githubusercontent.com/95366111/168562219-6eb56208-440c-4c43-aa80-002aa1ec7b94.png)

2022-05-27 08:39 UTC, nurul-umbhiya approved these changes

2022-05-27 08:40 UTC, merged