Bank withdrawal information update require fields and labels.
weDevsOfficial/dokan pull request #1675
Opened 2022-08-12 04:07 UTC by Aunshon

### All Submissions:

* [ ] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [ ] My code satisfies feature requirements
* [ ] My code is tested
* [ ] My code passes the PHPCS tests
* [ ] My code has proper inline documentation
* [ ] I've included developer documentation (optional)
* [ ] I've added proper labels to this pull request

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

2022-08-29 02:51 UTC, nurul-umbhiya requested changes

2022-08-29 02:51 UTC, nurul-umbhiya commented on includes/Withdraw/functions.php
> +        if ( ( ! empty( $required_field ) && ! empty( $args[ $key ] ) ) || empty( $required_field ) ) {
we can't be sure if account is connected if required_field variable is empty

2022-08-29 02:51 UTC, nurul-umbhiya commented on includes/Withdraw/functions.php
> +            'bank_name'      => '',
Add relevant error message for these fields

2022-08-29 02:51 UTC, nurul-umbhiya commented on includes/Dashboard/Templates/Settings.php
> +            foreach ( $payment_fields as $key => $payment_field ) {
since is_disconnect is required for each condition, can we add this on top of foreach?

2022-08-29 02:51 UTC, nurul-umbhiya commented on includes/Dashboard/Templates/Settings.php
> +                } else if ( ! $is_disconnect && ! empty( $payment_field ) && $key === 'ac_type' && ! in_array( $post_data['settings']['bank'][ $key ], [ 'personal', 'business' ] ) ) {
can we add some comments here describing what we are achieving here?

2022-09-09 02:54 UTC, nurul-umbhiya approved these changes

2022-09-13 10:18 UTC, shashwatahalder01 commented
Scenario: 
Vendor progress bar isn't increasing without providing these fields (Account Holder, Account Type, Account Number, Routing Number), whether these fields are required or not.

Steps to reproduce:
1. Remove required from one or more of these fields (Account Holder, Account Type, Account Number, Routing Number)
2. Fill up only required fields
3. Click add account
4. Account is connected [but the progress bar doesn't increase]

2022-09-20 04:32 UTC, merged