Feat/Added address fields on the vendor registration form
weDevsOfficial/dokan pull request #1735
Opened 2022-10-23 15:49 UTC by tanjiralmamun

### All Submissions:

* [x] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [x] My code satisfies feature requirements
* [x] My code is tested
* [ ] My code passes the PHPCS tests
* [ ] My code has proper inline documentation
* [ ] I've included developer documentation (optional)
* [ ] I've added proper labels to this pull request

### Changes proposed in this Pull Request:

Added the Store Address fields on the vendor registration form with an admin setting.

Closes #.

### How to test the changes in this Pull Request:

1. Enable the `Enable Address Fields` option from the `Dokan > General` setting screen
2. Registration as a vendor from the `My Account` page to see the changes

Screenshots:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34626059/197401923-f7b66121-7e9e-4595-96f9-41c27a5c17a7.png">
<img width="774" alt="image" src="https://user-images.githubusercontent.com/34626059/197402001-2471c2c7-903d-4f5f-83c2-99b68566c4c6.png">

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

2022-12-01 03:29 UTC, shashwatahalder01 commented
Scenario:
location input fields should follow woocommerce selling location settings

Steps to reproduce:
1. restrict selling location to specific countries
2. go to vendor reg from

Screenshot:
<img width="231" alt="af0" src="https://user-images.githubusercontent.com/82957718/204959280-4f9a98e7-2d40-4203-a8c8-5005e9fc6cce.png">
<img width="353" alt="af1" src="https://user-images.githubusercontent.com/82957718/204959285-9d4c81a4-dbdf-4150-a672-8b28197b182b.png">

2022-12-01 03:36 UTC, shashwatahalder01 commented
Scenario:
profile progress bar is not increasing if completed form reg form

Steps to reproduce:
1. complete address from reg from
2. see progress completion bar

Screenshot:
<img width="585" alt="af3" src="https://user-images.githubusercontent.com/82957718/204960116-ac5aa3f9-448a-46c8-b179-b83692c8da48.png">

2022-12-01 03:40 UTC, shashwatahalder01 commented
Scenario:
address input fields aren't on vendor reg shortcode

Screenshot:
<img width="286" alt="af4" src="https://user-images.githubusercontent.com/82957718/204960547-e867dd6c-6a63-4199-9c3b-c22212163e8f.png">

2022-12-01 03:47 UTC, shashwatahalder01 commented
Scenario:
If the address field is enabled on the vendor reg form, users get two address input forms: one on the reg form and another on the vendor setup wizard which is redundant. There should be only one address input field for vendor sign-up.

Screenshot:
<img width="290" alt="af2" src="https://user-images.githubusercontent.com/82957718/204961264-e4021e8f-ccda-4472-b584-851a13743147.png">
<img width="165" alt="af5" src="https://user-images.githubusercontent.com/82957718/204961267-77983c4e-2680-4b42-ba86-b188d6bc99b2.png">

2023-01-10 03:33 UTC, nurul-umbhiya requested changes

2023-01-10 03:33 UTC, nurul-umbhiya commented on assets/js/vendor-address.js
> +    var dokan_address_wrapper = $( '.dokan-address-fields' );
use let/const instead of var while possible,

2023-01-10 03:33 UTC, nurul-umbhiya commented on templates/global/seller-registration-form.php
> +    if ( $is_address_enabled == 'on' ) {
directly use `if ( 'on' === dokan_get_option( 'enabled_address_on_reg', 'dokan_general', 'on' ); ) `

2023-01-10 03:33 UTC, nurul-umbhiya commented on templates/account/vendor-registration.php
> +    if ( $is_address_enabled == 'on' ) {
directly use `if ( 'on' === dokan_get_option( 'enabled_address_on_reg', 'dokan_general', 'on' ) )`

2023-01-10 03:33 UTC, nurul-umbhiya commented on includes/Assets.php
> +            'dokan-vendor-address'      => [
fix all phpcs related issues

2023-01-10 03:33 UTC, nurul-umbhiya commented on templates/global/seller-registration-form.php
> +    if ( $is_address_enabled == 'on' ) {
Also default value should be `off` as you set `off` as default value on corresponding settings

2023-01-10 03:33 UTC, nurul-umbhiya commented on assets/js/vendor-address.js
> +    var dokan_address_wrapper = $( '.dokan-address-fields' );
Have you removed the corresponding duplicate js code from codebase?

2023-02-09 09:44 UTC, nurul-umbhiya approved these changes

2023-02-13 02:58 UTC, merged