Enhance/cerate reverse withdraw by admin
weDevsOfficial/dokan pull request #1910
Opened 2023-06-07 07:21 UTC by Aunshon

### All Submissions:

* [ ] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [ ] My code satisfies feature requirements
* [ ] My code is tested
* [ ] My code passes the PHPCS tests
* [ ] My code has proper inline documentation
* [ ] I've included developer documentation (optional)
* [ ] I've added proper labels to this pull request

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

2023-06-08 03:18 UTC, nurul-umbhiya requested changes

2023-06-08 03:18 UTC, nurul-umbhiya commented on src/admin/components/AddReverseWithdraw.vue
> +            if ( ('debit' === this.withdrawalType && ! this.withdrawalAmount) || ('credit' === this.withdrawalType && ! this.withdrawalAmount) ) {
withdraw amount should follow wooCommerce number formatting guideline.

2023-06-08 03:18 UTC, nurul-umbhiya commented on src/admin/components/AddReverseWithdraw.vue
> +            let debit = 'debit' === this.withdrawalType ? this.withdrawalAmount : 0;
since we are validating data beforehand, below data can be optimized further.

2023-06-08 03:18 UTC, nurul-umbhiya commented on src/admin/components/AddReverseWithdraw.vue
> +<style lang='less'>
use `scoped` attribute

2023-07-04 07:17 UTC, shashwatahalder01 commented
Scenario:
add reverse withdraw modal isn't responsive.


Screen
<img width="572" alt="Screenshot at Jul 04 11-41-45" src="https://github.com/weDevsOfficial/dokan/assets/82957718/26f1eddc-656d-4423-947b-928331a039ae">
<img width="485" alt="Screenshot at Jul 04 13-14-32" src="https://github.com/weDevsOfficial/dokan/assets/82957718/8e155bab-250e-46c7-a58a-bc32d5cf10dc">
shot:

2023-07-04 07:34 UTC, shashwatahalder01 commented
Scenario:
kindly add tooltip for debit & credit Withdrawal Balance Type.

Screenshot:
<img width="457" alt="Screenshot at Jul 04 13-33-06" src="https://github.com/weDevsOfficial/dokan/assets/82957718/07468038-5123-46db-ab71-770882c75270">

2023-07-04 07:37 UTC, shashwatahalder01 commented
Scenario:
order id is not showing in Transaction ID column for admin add reverse withdrawal

Steps to reproduce:
1. go to admin > reverse withdrawal > add new reverse withdrawal
2.  sele order for Transection Type
3. complete rest of the submit process
4.  go to vendor reversewithdrawal details

Screenshot:
<img width="636" alt="Screenshot at Jul 04 13-16-14" src="https://github.com/weDevsOfficial/dokan/assets/82957718/40351693-4667-480b-a454-108582125758">

2023-07-24 04:12 UTC, merged