feat: one step product creation
weDevsOfficial/dokan pull request #1915
Opened 2023-06-12 10:14 UTC by shohag121

### All Submissions:

* [x] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [x] My code satisfies feature requirements
* [ ] My code is tested
* [ ] My code passes the PHPCS tests
* [ ] My code has proper inline documentation
* [ ] I've included developer documentation (optional)
* [ ] I've added proper labels to this pull request

### Changes proposed in this Pull Request:

* Added a settings field `One Page Product Creation`. If the setting is on then disable popup settings will be hidden.
<img width="928" alt="Screenshot 2023-06-12 at 3 34 07 PM" src="https://github.com/weDevsOfficial/dokan/assets/5476784/22808ef6-3522-4178-8153-1e740b3074ce">

* One-page/single-step product addition added. this closes #1508
![image](https://github.com/weDevsOfficial/dokan/assets/5476784/7e50eb62-d62b-4883-b8b9-e5179ea69053)

### How to test the changes in this Pull Request:

1. Please check issue #1508

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

**feat**: One Step product addition
Previously, vendors have to use a product popup or a limited field page to create a product. Now Dokan is giving one step single-page product addition experience.

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

2023-06-12 11:40 UTC, nurul-umbhiya commented
Related Issue: https://github.com/weDevsOfficial/dokan-pro/issues/1234

2023-06-20 02:45 UTC, nurul-umbhiya requested changes

2023-06-20 02:45 UTC, nurul-umbhiya commented on assets/src/js/product-editor.js
> +            let dokanOnePage = '1' === $('#dokan_one_page').val();
this can be obtain from i18n data

2023-06-20 02:45 UTC, nurul-umbhiya commented on assets/src/js/product-editor.js
> +                if ( 'edit' === action && dokanOnePage ) {
we can early return if dokanOnePage is not enabled, Also, dokanOnePage doesn't make sense, kindly consider changing this variable.

2023-06-20 02:45 UTC, nurul-umbhiya commented on templates/products/edit-product-single.php
> +    $post_excerpt   = $post->post_excerpt;
wouldn't it be better if we created auto-draft product via js and redirect to product edit page?
we can determine if this is a new product or not via post_status = auto-draft?

2023-06-20 07:04 UTC, shohag121 commented
Tareq Bhaya instructed us to remove the admin settings related to product creation.

2023-07-18 08:10 UTC, tanjiralmamun commented
> Tareq Bhaya instructed us to remove the admin settings related to product creation.

@shohag121 Bhai, many users still like and want the use the popup form. Also, many users are already used to it. So, removing an existing feature without prior notice or removing the popup form completely would not be a good decision in my opinion.

2023-07-18 09:24 UTC, shohag121 commented
@tanjiralmamun Bhai,

Initially, The feature had the support to choose the style of the product creation page. Tareq Bhaya instructed us to remove the settings after seeing it.

@nurul-umbhiya Bhai Already ran a user opinion poll in our FB group discussing it.

You are welcome to start a new discussion with @shams-sadek1981 Bhai and @Mohaiminulislam1989 Bhai. That would be best.

2023-07-19 04:57 UTC, shashwatahalder01 commented
Scenario:
Popup stills open for add new product if vendor doesn't have any previous products


Screenshot:
<img width="520" alt="Screenshot at Jul 19 10-46-03" src="https://github.com/weDevsOfficial/dokan/assets/82957718/a1b0097c-4c47-4de2-837c-c1ac51f1b8bf">
<img width="496" alt="Screenshot at Jul 19 10-46-17" src="https://github.com/weDevsOfficial/dokan/assets/82957718/4959f7ff-12f7-4cc8-bee8-4d088531e5b3">

2023-07-19 06:09 UTC, shashwatahalder01 commented
Scenario:
product gets published directly on dokan lite, even though publish directly is disabled for that vendor

1. add a vendor 
2. add a product for that vendor

Screenshot:
![Screenshot at Jul 19 11-58-23](https://github.com/weDevsOfficial/dokan/assets/82957718/8ee23a35-3a5e-4c62-9c22-7b4523050d1d)

2023-07-19 07:05 UTC, shashwatahalder01 commented
Scenario:
wholesale setting doen't load on single page product create form

Steps to recreate:
1. enable wholesale from admin 
2. go to product create form
3. check wholesale checkbox

Screenshot:
![Screenshot at Jul 19 12-48-16](https://github.com/weDevsOfficial/dokan/assets/82957718/eb559456-9d52-48fd-8c20-facdca7c7bed)
Should be:
![Screenshot at Jul 19 13-00-54](https://github.com/weDevsOfficial/dokan/assets/82957718/2cec8c22-f775-4ec8-be5e-6144d6e6ee87)

2023-07-19 07:08 UTC, shashwatahalder01 commented
Scenario:
 All  sub options regarding rma type loading at the same time on single page product create form. Should only load sub options based on RMA type

Steps to recreate:
1. Enable RMA from both Admin and Vendor
2.go to product create form
3.go to rma section [all options are loading]

Screenshot:

![Screenshot at Jul 19 13-02-00](https://github.com/weDevsOfficial/dokan/assets/82957718/7682a510-5e95-4a56-a11c-f574bcf92565)

2023-07-27 04:12 UTC, shohag121 commented
@shashwatahalder01 Bhai, Issues are fixed.

2023-08-14 04:23 UTC, shohag121 commented
@Mohaiminulislam1989 Bhaya, Product creation page-related settings re-added.

![Screenshot 2023-08-14 at 10 19 18 AM](https://github.com/weDevsOfficial/dokan/assets/5476784/bbfa0b53-2767-4d01-878b-c8349b32f3ff)

2023-08-29 10:29 UTC, merged