Module/form manager
weDevsOfficial/dokan pull request #2098
Opened 2023-12-11 03:29 UTC by nurul-umbhiya

### All Submissions:

* [ ] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [ ] My code satisfies feature requirements
* [ ] My code is tested
* [ ] My code passes the PHPCS tests
* [ ] My code has proper inline documentation
* [ ] I've included related pull request(s) (optional)
* [ ] I've included developer documentation (optional)
* [ ] I've added proper labels to this pull request

### Changes proposed in this Pull Request:

### Related Pull Request(s)

* Full PR Link

### Closes 

* Closes #

### How to test the changes in this Pull Request:

* Steps or issue link

### Changelog entry

*Title*

Detailed Description of the pull request. What was previous behaviour
and what will be changed in this PR.

### Before Changes

Describe the issue before changes with screenshots(s).

### After Changes

Describe the issue after changes with screenshot(s).

### Feature Video (optional)

Link of detailed video if this PR is for a feature.

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

2024-01-19 04:41 UTC, Mohaiminulislam1989 commented
@devAsadNur @nurul-umbhiya What is the status of this PR?

2024-01-19 04:43 UTC, nurul-umbhiya commented
@Mohaiminulislam1989 bhai minimum of 15 days of works left. Pro code rewrite is going on.

2024-01-19 04:46 UTC, Mohaiminulislam1989 commented
@nurul-umbhiya vai can we target releasing this by February 10?

2024-01-19 04:48 UTC, nurul-umbhiya commented
@Mohaiminulislam1989 No bhai. I'm guessing 25th February. after developing this feature, we need through testing. Also, we need to integrate this feature with new Vendor Dashboard.

2024-01-19 04:50 UTC, Mohaiminulislam1989 commented
Hope we will not miss the release. Thank you for prompt reply.

2024-04-15 11:54 UTC, devAsadNur commented
For the `Product Form Customize` feature, the task has been done from my end. Now, @nurul-umbhiya Bhai is working on rewrite.

CC: @Mohaiminulislam1989 Bhai, @shams-sadek1981 Bhai

2024-04-30 09:47 UTC, nurul-umbhiya commented
Product Form Manager-related rewrite is completed from my end. @Mohaiminulislam1989 @shams-sadek1981

2024-08-27 06:37 UTC, mrabbani requested changes

2024-08-27 06:37 UTC, mrabbani commented on includes/ProductForm/Factory.php
> +
Why are we using singleton where all methods and properties are statics?

2024-08-29 06:37 UTC, mrabbani requested changes

2024-08-29 06:37 UTC, mrabbani commented on includes/Product/Manager.php
> +    public function delete( $product_id, $force = false ) {
Pls update the Doc blocks for return type

2024-09-12 05:37 UTC, shashwatahalder01 commented
Scenario:
layout is broken

Screenshot:
<img width="913" alt="Screenshot at Sep 09 16-35-30" src="https://github.com/user-attachments/assets/592a66bc-34e8-47b9-b868-e85df60f0006">
![Screenshot at Sep 11 15-07-16](https://github.com/user-attachments/assets/f55e72b7-e39b-43a5-92c9-8725f8795d88)

2024-09-12 05:39 UTC, shashwatahalder01 commented
Scenario:
Help text is removed for SKU

Screenshot:
![Screenshot at Sep 10 16-20-19](https://github.com/user-attachments/assets/df292a13-de4b-40ce-8524-6961824e1ee2)
![Screenshot at Sep 10 16-20-00](https://github.com/user-attachments/assets/ba3e94e9-757d-409a-8884-298be4b7b8cd)

2024-09-12 05:41 UTC, shashwatahalder01 commented
Scenario:
Default value is removed for low stock threshold.

Screenshot:
![Screenshot at Sep 10 16-24-26](https://github.com/user-attachments/assets/b02a440c-1064-420e-b7b0-68fc8e8324f4)
Develop:
![Screenshot at Sep 10 16-24-11](https://github.com/user-attachments/assets/93ea69c6-d377-42c8-9f22-48a273e11372)

2024-09-12 05:43 UTC, shashwatahalder01 commented
scenario:
Console error on product edit page

Scenario:
![Screenshot at Sep 11 15-04-46](https://github.com/user-attachments/assets/154db248-20fe-49b3-a708-e44def81d61b)

2024-09-12 05:54 UTC, shashwatahalder01 commented
Scenario:
PHP warning on Booking product edit.

PHP Warning:
```
[12-Sep-2024 05:47:48 UTC] PHP Warning:  Undefined variable $required_symbol in /Users/rk/Sites/dokan5/wp-content/plugins/dokan/templates/products/dokan-category-header-ui.php on line 25
[12-Sep-2024 05:47:48 UTC] PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /Users/rk/Sites/dokan5/wp-includes/kses.php on line 1805
```

Screenshot:
![Screenshot at Sep 12 11-49-01](https://github.com/user-attachments/assets/ff3864c2-c63d-4dd2-a056-cb8d7d780fb7)
![Screenshot at Sep 12 11-51-59](https://github.com/user-attachments/assets/27b1d4c8-f554-4a97-aef2-d45c77e4a0ea)

2024-09-12 06:08 UTC, shashwatahalder01 commented
Scenario:
No required indicator on booking add new product, but rules are applying

Screenshot:
![Screenshot at Sep 12 11-55-34](https://github.com/user-attachments/assets/e0bb8f36-d45d-4403-b157-1ac0b6a68718)
![Screenshot at Sep 12 12-07-50](https://github.com/user-attachments/assets/2f93c9f2-5fb3-4412-bde4-fe658f3165c4)

2024-09-12 06:13 UTC, shashwatahalder01 commented
Scenario:
The required error message should be consistent. (see booking product save)

Screenshot:
![Screenshot at Sep 10 16-28-18](https://github.com/user-attachments/assets/e7c84259-f341-4a56-b052-39ee21bf0738)
![Screenshot at Sep 12 12-07-50](https://github.com/user-attachments/assets/0c59ba99-741d-4c69-8f85-f3e5eaa69243)

2024-09-17 08:14 UTC, shashwatahalder01 commented
Scenario: 
Vendors can't reset the discount schedule once it is saved.

Steps to reproduce:
1. save a product with a discount schedule
2. try to cancel & save the product [schedule won't reset]

[Screencast](https://jam.dev/c/d88340ae-19b6-4f45-b0a0-491fc9c2ee0f)

2024-09-17 09:45 UTC, shashwatahalder01 commented
Scenario:
 vendors can't add downloadable product.

Steps to reproduce:
1. fill out a product create form with downloadable options 
2. try to save it [display file permission issue]

[Screencast](https://jam.dev/c/396c8bf5-b4b6-46cf-ac6c-144881d4df7e)

2024-09-17 10:19 UTC, shashwatahalder01 commented
Scenario:
Several product type options are missing from the product type dropdown. 

Screenshot:
<img width="876" alt="Screenshot at Sep 17 16-16-32" src="https://github.com/user-attachments/assets/e87f927e-e218-4ce7-83c8-4c07a84a0c51">
<img width="857" alt="Screenshot at Sep 17 16-17-15" src="https://github.com/user-attachments/assets/2275c95a-4cc3-48a4-9994-b2397674badb">

2024-09-17 11:11 UTC, shashwatahalder01 commented
Scenario:
product size data(weight, length, width,...) doesn't stored upon product save

Steps to reproduce:
1.  create a product with shipping data & fill up product size inputs

[Screencast](https://jam.dev/c/90f278e8-595c-46f7-8aeb-fe9dac9b423b)

2024-09-17 11:17 UTC, shashwatahalder01 commented
Scenario:
product tax data(status, class) doesn't stored upon product save

Steps to reproduce:

1. create a product with tax data 



[Screencast](https://jam.dev/c/bc669bbe-6980-451a-ac72-d9ca7d16e8b9)

2024-09-17 11:30 UTC, shashwatahalder01 commented
Scenario:
product addon data doesn't stored upon product save

Steps to reproduce:
1. create a product with product addon data

[Screencast](https://jam.dev/c/a631eb8b-1e5f-4b40-bf7f-c1ad3a9a5efb)

2024-09-17 11:33 UTC, shashwatahalder01 commented
Scenario:
Vendors can't product attributes while creating a product.

Steps to reproduce:
1. try to add attributes while adding or editing a product

[Screencast](https://jam.dev/c/5474fef6-0e1f-42bc-9ce6-ef95c2faa47b)

2024-09-17 11:40 UTC, shashwatahalder01 commented
Scenario:
product bulk discount data doesn't stored upon product save

Steps to reproduce:
1. create a product with product bulk discount data

Screencast[https://jam.dev/c/6f77f720-749a-4aec-864f-67f0e0e72247](url)

2024-11-12 09:27 UTC, mrabbani approved these changes

2026-05-18 07:08 UTC, kzamanbd commented
According to the release related to PR https://github.com/getdokan/dokan/pull/3083, we are considering this issue resolved and have closed it.

2026-05-18 07:08 UTC, closed without merging