New/currency switcher support
weDevsOfficial/dokan pull request #994
Opened 2020-12-15 04:44 UTC by alamgircsebd

2020-12-19 16:50 UTC, kapilpaul requested changes

2020-12-19 16:50 UTC, kapilpaul commented on includes/wc-functions.php
> +    add_action( 'woocommerce_order_status_completed', 'dokan_woocs_recalculate_order_payment_completed', 1 );
please move actions outside of the condition.

2020-12-22 12:15 UTC, FaraziF commented
When switch currency, only in new order currency has been changing. Reference: [image](https://prnt.sc/w7rzf6)

2020-12-23 14:41 UTC, FaraziF commented
WC Currency Switcher plugin is not working properly even without Dokan. We need to test this plugin first, list the issues and then consider the integration. So we shouldn't merge this pull request now.

2021-01-20 08:52 UTC, closed without merging